/** PROPONENTES */
export const SET_PROPONENTE = 'SET_PROPONENTE';

export const SET_PROPONENTES = 'SET_PROPONENTES';

export const INSERT_PROPONENTE = 'INSERT_PROPONENTE';

export const UPDATE_PROPONENTE = 'UPDATE_PROPONENTE';

export const DELETE_PROPONENTE = 'DELETE_PROPONENTE';

export const SET_PROPONENTE_ENDERECO = 'SET_PROPONENTE_ENDERECO';

export const SET_PROPONENTE_TELEFONE = 'SET_PROPONENTE_TELEFONE';

export const DELETE_PROPONENTE_TELEFONE = 'DELETE_PROPONENTE_TELEFONE';

export const SET_PROPONENTE_EMAIL = 'SET_PROPONENTE_EMAIL';

export const DELETE_PROPONENTE_EMAIL = 'DELETE_PROPONENTE_EMAIL';

export const SET_PROPONENTE_MIDIA_SOCIAL = 'SET_PROPONENTE_MIDIA_SOCIAL';

export const UPDATE_PROPONENTE_MIDIA_SOCIAL = 'UPDATE_PROPONENTE_MIDIA_SOCIAL';

export const SET_PROPONENTE_ARQUIVO = 'SET_PROPONENTE_ARQUIVO';

export const RESET_PROPONENTE_ARQUIVO = 'RESET_PROPONENTE_ARQUIVO';

export const DELETE_PROPONENTE_ARQUIVO = 'DELETE_PROPONENTE_ARQUIVO';

export const SET_PROPONENTE_DIRIGENTE = 'SET_PROPONENTE_DIRIGENTE';

export const UPDATE_PROPONENTE_DIRIGENTE = 'UPDATE_PROPONENTE_DIRIGENTE';

/** DIRIGENTE */

export const SET_DIRIGENTE = 'SET_DIRIGENTE';

export const SET_DIRIGENTE_ENDERECO = 'SET_DIRIGENTE_ENDERECO';

export const SET_DIRIGENTE_TELEFONE = 'SET_DIRIGENTE_TELEFONE';

export const DELETE_DIRIGENTE_TELEFONE = 'DELETE_DIRIGENTE_TELEFONE';

export const SET_DIRIGENTE_EMAIL = 'SET_DIRIGENTE_EMAIL';

export const DELETE_DIRIGENTE_EMAIL = 'DELETE_DIRIGENTE_EMAIL';

export const SET_DIRIGENTE_ARQUIVO = 'SET_DIRIGENTE_ARQUIVO';

export const DELETE_DIRIGENTE_ARQUIVO = 'DELETE_DIRIGENTE_ARQUIVO';

export const DELETE_DIRIGENTE = 'DELETE_DIRIGENTE';

/** NATUREZAS */
export const SET_NATUREZAS = 'SET_NATUREZAS';

/** RESPONSAVEIS */
export const SET_RESPONSAVEL_PENDENTE = 'SET_RESPONSAVEL_PENDENTE';

export const SET_RESPONSAVEIS_VINCULADOS = 'SET_RESPONSAVEIS_VINCULADOS';

export const SET_RESPONSAVEL_VINCULADO = 'SET_RESPONSAVEL_VINCULADO';

export const DELETE_RESPONSAVEL_PENDENTE = 'DELETE_RESPONSAVEL_PENDENTE';

export const DELETE_RESPONSAVEL_VINCULADO = 'DELETE_RESPONSAVEL_VINCULADO';

export const SET_AGENTE = 'SET_AGENTE';
export const SET_DOCUMENTOS_AGENTE = 'SET_DOCUMENTOS_AGENTE';
export const UPDATE_DOCUMENTOS_AGENTE = 'UPDATE_DOCUMENTOS_AGENTE';
export const DELETE_DOCUMENTOS_AGENTE = 'DELETE_DOCUMENTOS_AGENTE';
