export const SET_SNACKBAR = 'SET_SNACKBAR';

export const SET_TEMA_APP = 'SET_TEMA_APP';

export const SET_COR_TEMA = 'SET_COR_TEMA';

export const SET_MODO_TEMA = 'SET_MODO_TEMA';

export const SET_MENU_APP_STATUS = 'SET_MENU_APP_STATUS';

export const SET_USUARIO_LOGADO = 'SET_USUARIO_LOGADO';

export const SET_PRIMARY_DRAWER = 'SET_PRIMARY_DRAWER';

export const SET_PRIMARY_DRAWER_STATUS = 'SET_PRIMARY_DRAWER_STATUS';

export const SET_SECONDARY_DRAWER = 'SET_SECONDARY_DRAWER';

export const SET_SECONDARY_DRAWER_STATUS = 'SET_SECONDARY_DRAWER_STATUS';

export const SET_THEME_DRAWER = 'SET_THEME_DRAWER';

export const SET_PERFIL_ATIVO = 'SET_PERFIL_ATIVO';

export const SET_MENU = 'SET_MENU';

export const UPDATE_MENU = 'UPDATE_MENU';
